#!/usr/bin/env bash
# Displays information about subdomains.

domain_datas () {
    url="$2.$1"
    line="$(dig "$url" | grep -Eo "$2\.$1.+([0-9]+\.)[0-9]+")"
    echo "$2 $line" |  awk '{print "The subdomain", $1, "is a", $5, "record and points to", $6}'
}

if [ "$#" == 2 ]; then
    domain_datas "$1" "$2"
elif [ "$#" == 1 ]; then
    list=("www" "lb-01" "web-01" "web-02")
    for sub in "${list[@]}"; do
        domain_datas "$1" "$sub"
    done
fi
