#!/usr/bin/env bash
# Configures a Web Server (Nginx) with a custom header

apt-get update -y && apt-get upgrade -y
apt-get install -y nginx
ufw allow 'Nginx HTTP'
mkdir -p /var/www/html/
chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

HOSTNAME="$(hostname)"
SERVER_CONFIG=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html;

	server_name _;
	add_header X-Served-By $HOSTNAME;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}

	error_page 404 /404.html;
	location = /404.html {
		internal;
	}
}"

bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-available/default"

if [ -L /etc/nginx/sites-enabled/default ]; then
	rm -f /etc/nginx/sites-enabled/default
fi
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

if [ "$(pgrep -c nginx)" -le 0 ]; then
	service nginx start
else
	service nginx restart
fi
