#!/usr/bin/env bash
# Installs and setup haproxy

apt-get update -y && apt-get upgrade -y
apt-get install -y haproxy

LOAD_BALANCER=\
"
backend load_balancer
    balance roundrobin
    server web-01 web-01.lexcraft.tech:80 check
    server web-02 web-02.lexcraft.tech:80 check
 
frontend http
    bind *:80
    mode http

    default_backend load_balancer"

bash -c "echo -e '$LOAD_BALANCER' >> /etc/haproxy/haproxy.cfg"
if [ "$(pgrep -c haproxy)" -le 0 ]; then
    service haproxy start
else
    service haproxy restart
fi
