#!/usr/bin/env bash
# Generates a MySQL dump and creates a compressed archive out of it.

if [ "$#" -ne 1 ]; then
	echo "Usage: $0 <mysql_root_password>"
	exit 1
fi

ADMIN_PASSWORD="$1"
BACK_UP_FILE="backup.sql"
ARCHIVE_FILE="$(date +'%d-%m-%Y').tar.gz"

# Generate a MySQL dump on all databases.
mysqldump -u root -p"$ADMIN_PASSWORD" --all-databases > "$BACK_UP_FILE"

# Generate an archive of the MySQL Databases.
tar -cvzf "$ARCHIVE_FILE" "$BACK_UP_FILE"
