#!/usr/bin/env bash
# Creates a file '/var/run/myscript.pid' containing its PID and
#+ echo 'To infinity and beyond' indefinetly.
# Displays 'I hate the kill command' when receiving a SIGTERM signal
# Displays 'Y U no love me?!' when receiving a SIGINT signal
# Deletes the file '/var/run/myscript.pid' and terminates itself when receiving a
#+ SIGQUIT or SIGTERM signal

trap "rm -rf /var/run/myscript.pid ; echo 'I hate the kill command' ; exit" 15
trap "echo 'Y U no love me?!' ; exit" 2

PID=$( pgrep -f $0 )
export FILE="/var/run/myscript.pid"
echo "$PID" > "$FILE"

i=1
while [ "$i" -eq "1" ]
do
	echo "To infinity and beyond"
	sleep 2
done
