#!/usr/bin/env bash
# Manages the 'manage_my_process' program
# When 'start' is passed as argument to program:
#	Starts 'manage_my_process'
# 	Creates a file containing its PID in /var/run/my_process.pid
#	Displays manage_my_process started
#
# When 'stop' is passed as argument to program:
#	Stops 'manage_my_process'
#	Deletes the file '/var/run/my_process.pid
#	Displays 'manage_my_process stopped'
#
# When 'restart' is passed as argument to program:
#	Stops 'manage_my_process'
#	Deletes the file '/var/run/my_process.pid'
#	Starts 'manage_my_process'
#	Creates a file containing its PID in '/var/run/my_process.pid'
#	Displays 'manage_my_process restarted'
#
# If any other or no arguments were passed to program:
#	Displays 'Usage: manage_my_process {start|stop|restart}

PID_FILE="/var/run/my_process.pid"

if [ "$#" -eq "0" ]
then
	echo "Usage: manage_my_process {start|stop|restart}"
else
	case "$1" in
		"start")
			./manage_my_process &
			echo "$!" > "$PID_FILE"
			echo "manage_my_process started"
			;;
		"stop")
			kill "$( cat $PID_FILE )"
			sudo rm -rf "$PID_FILE"
			echo "manage_my_process stopped"
			;;
		"restart")
			kill "$( cat $PID_FILE )"
			sudo rm -rf "$PID_FILE"
			./manage_my_process &
			echo "$!" > "$PID_FILE"
			echo "manage_my_process restarted"
			;;
		*)
			echo "Usage: manage_my_process {start|stop|restart}"
			;;
	esac
fi
