#!/usr/bin/env bash
# An infinite loop that echos 'To infinity and beyond' and
# 'I am invicible!!!' when an SIGTERM signal is rescieved.

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invicible!!!"' 15
done
