#!/usr/bin/env bash
# Prints number from 1 through 20 and prints
#+ 'bad luck from China' after iteration 4, 'bad luck from
#+ Japan' after iteration 9 and 'bad luck from Italy' after iteration 17 followed by numbers.

i=1
while [ "$i" -ne "21" ]
do
	echo "$i"
	if [ "$i" -eq "4" ]
	then
		echo "bad luck from China"
	elif [ "$i" -eq "9" ]
	then
		echo "bad luck from Japan"
	elif [ "$i" -eq "17" ]
	then
		echo "bad luck from Italy"
	fi
	let "i = $i + 1"
done

exit 0
