#!/usr/bin/env bash
# Prints number from 1 through 20 and prints
#+ 'bad luck from China' after iteration 4, 'bad luck from
#+ Japan' after iteration 9 and 'bad luck from Italy' after iteration 17 followed by numbers.

i=1
while [ "$i" -ne "21" ]
do
	echo "$i"
	case "$i" in
		"4")
			echo "bad luck from China"
			;;
		"9")
			echo "bad luck from Japan"
			;;
		"17")
			echo "bad luck from Italy"
	esac
	(( i++ ))
done

exit 0
