#!/usr/bin/env bash
# Displays the content of the current directory in a list
#+ format.
# Where only the part of the name after the first dash is
#+ displayed.

LS=$(ls)
for i in $LS
do
	FILE=$( echo "$i" | cut -d '-' -f 2- )
	echo "$FILE"
done

exit 0
