#!/usr/bin/env bash
# Displays the content of the current directory in a list
#+ format.
# Where only the part of the name after the first dash is
#+ displayed.

for i in `ls`
do
	FILE=`echo $i | cut -d '-' -f 2-`
	echo $FILE
done

exit 0
