#!/usr/bin/env bash
# run apache on designated container

echo "Hello Holberton" > /var/www/html/index.html
sed -i '/Listen 80/a Listen 0.0.0.0:8080' /etc/apache2/ports.conf
sed -i '/VirtualHost>/a <VirtualHost *:8080>\nServerAdmin webmaster@localhost\nDocumentRoot /var/www/html\n</VirtualHost>' /etc/apache2/site-available/000-default.config
service apache2 start
